#!/bin/bash

# This script prints a range of numbers
# Usage: count [-r] [-b n] [-s n] stop
# -b gives the number to begin with (default: 0)
# -r reverses the count
# -s sets step size (default: 1)
# counting will stop at stop

# ex: ./count -s 2 10

usage () {
	cat <<END
count [-r] [-b n] [-s n] stop

Print each number up to stop, beginning at 0
	-b gives the number to begin with (default: 0)
	-r reverses the count
	-s sets step size (default: 1)
END
}

error () {
	echo "Error: $1"
	usage
	exit $2
} >&2

isnum () {
	echo "what??"
	declare -r num_re='^[0-9]+$'
	# In bash, numbers starting with a 0 are assumed to be octal numbers
	# After 0, may com 1 or more characters (digits)
	# dot (.) means any character
	declare -r octal_re='^0(.+)'
	num_error="ok"
	# verify if first agument is actualy a number
	echo "hhh"
	if [[ $1 =~ $num_re ]]; then
			if [[ $1 =~ $octal_re ]]; then
				echo "hhheeee"
				# BASH_REMATCH contains group of matches, in this case BASH_REMATCH[1] is the second match rule (^0(.+))
				num_error="$1 is not a number, did you mean ${BASH_REMATCH[1]}?"
				return 1
			fi
	else
		num_error="$1 is not a number"
		return 1
	fi

	return 0
}

declare reverse=""
declare -i begin=0
declare -i step=1

while getopts ":b:s:r" opt; do # b, s, r are the options to be accepted and will be saved on opt
	case $opt in
		r)
			reverse="yes"
			;;
		b)
			# [[ ${OPTARG} =~ ^[0-9]+$ ]] || { echo "${OPTARG} is not a number" >&2; exit 1; }
			isnum ${OPTARG} || error "${OPTARG} is not a number" 1
			start="${OPTARG}"
			;;

		h)
			usage
			exit 0
			;;
		s)
			isnum ${OPTARG} ]] || error "${OPTARG} is not a number" 1
			step="${OPTARG}"
			;;
		:)
			echo "Option -${OPTARG} is missing argument"
			usage
			exit 1
			;;
		\?)  # either for not acceptable arguments or missing argument
			echo "Unkown option: -${OPTARG}" >&2
			usage
			exit 1
			;;
	esac
done

# gives the index of the next option to handle
# shift all arguments and make sure that last argument in in $1
shift $(( OPTIND -1 ))

# [[ $1 ]] || { echo "missing and argument" >&2; exit 1; }
[[ $1 ]] || error "missing and argument" 1
declare end="$1"

if [[ ! $reverse ]]; then
	for (( i=start; i <= end; i+=step )); do
		echo $i
	done
else
	for (( i=end; i >= start; i-=step )); do
		echo $i
	done
fi

exit 0
