#!/bin/bash

# create script

#help with condition, type: 'help [['; or 'help test'
# is there an argument?
if [[ ! $1 ]]; then
	echo "Missing argument"
	exit
fi

declare open_editor=""
if [[ $# -eq 1 ]]; then
	open_editor="true"
fi


# points to bin dir
declare -r bindir="${HOME}/_bin"



# check if dir already exists
if [[ ! -d $bindir ]]; then
	if mkdir "$bindir"; then
		echo "Created ${bindir}" >&2
	else
		echo "Could not create ${bindir}" >&2
		exit 1
	fi
fi

while [[ $1 ]]; do
	scriptname="$1"
	filename="${bindir}/${scriptname}"

	if [[ -e $filename ]]; then
		echo "File ${filemame} already exists" >&2
		shift
		continue
	fi

	if type "$scriptname" > /dev/null 2>&1; then
		echo "There is already a command with name ${scriptname}" >&2
		shift
		continue
	fi

	# create a script with a single line
	echo '#!/bin/bash' > "$filename"
	# add executable permission
	chmod u+x "$filename"

	shift
done


# open with editor
if [[ $open_editor ]]; then
	echo opening
	if [[ $EDITOR ]]; then
		$EDITOR "$filename"
	fi
else
	# '\' scapes the meaning of '$', so the variable name will be shown
	echo "Script create: not starting editor becuse \$EDITOR is not set"
fi
