#!/bin/bash

# Attemps to count the lines of output of any given command

declare -i count=0

count_lines () {
	while read -r; do
		((++count))
	done
	echo $count
}

# $* prints all arguments given to the command
# with the pipe, it runs inside a separate bash process
$ count will be local to that sub-shell and will not be visible to its parent processi
$* | count_lines
echo $count
